local M = {}

function M.setup(colors) end

-- -- HTML
-- htmlArg = { fg = colors.green },
-- htmlBold = { fg = colors.yellow, bold = true },
-- htmlEndTag = { fg = colors.cyan },
-- htmlH1 = { fg = colors.pink },
-- htmlH2 = { fg = colors.pink },
-- htmlH3 = { fg = colors.pink },
-- htmlH4 = { fg = colors.pink },
-- htmlH5 = { fg = colors.pink },
-- htmlH6 = { fg = colors.pink },
-- htmlItalic = { fg = colors.purple, italic = true },
-- htmlLink = { fg = colors.purple, underline = true },
-- htmlSpecialChar = { fg = colors.yellow },
-- htmlSpecialTagName = { fg = colors.cyan },
-- htmlTag = { fg = colors.cyan },
-- htmlTagN = { fg = colors.cyan },
-- htmlTagName = { fg = colors.cyan },
-- htmlTitle = { fg = colors.white },
--
-- -- Markdown
-- markdownBlockquote = { fg = colors.yellow, italic = true },
-- markdownBold = { fg = colors.orange, bold = true },
-- markdownCode = { fg = colors.green },
-- markdownCodeBlock = { fg = colors.orange },
-- markdownCodeDelimiter = { fg = colors.red },
-- markdownH2 = { link = "rainbow2" },
-- markdownH1 = { link = "rainbow1" },
-- markdownH3 = { link = "rainbow3" },
-- markdownH4 = { link = "rainbow4" },
-- markdownH5 = { link = "rainbow5" },
-- markdownH6 = { link = "rainbow6" },
-- markdownHeadingDelimiter = { fg = colors.red },
-- markdownHeadingRule = { fg = colors.comment },
-- markdownId = { fg = colors.purple },
-- markdownIdDeclaration = { fg = colors.cyan },
-- markdownIdDelimiter = { fg = colors.purple },
-- markdownItalic = { fg = colors.yellow, italic = true },
-- markdownLinkDelimiter = { fg = colors.purple },
-- markdownLinkText = { fg = colors.pink },
-- markdownListMarker = { fg = colors.cyan },
-- markdownOrderedListMarker = { fg = colors.red },
-- markdownRule = { fg = colors.comment },
-- ["@markup.heading.1.markdown"] = { link = "rainbowcol1" },
-- ["@markup.heading.2.markdown"] = { link = "rainbowcol2" },
-- ["@markup.heading.3.markdown"] = { link = "rainbowcol3" },
-- ["@markup.heading.4.markdown"] = { link = "rainbowcol4" },
-- ["@markup.heading.5.markdown"] = { link = "rainbowcol5" },
-- ["@markup.heading.6.markdown"] = { link = "rainbowcol6" },

return M
