local M = {}

function M.setup(colors) end
		-- -- Git Signs
		-- GitSignsAdd = { fg = colors.bright_green },
		-- GitSignsChange = { fg = colors.cyan },
		-- GitSignsDelete = { fg = colors.bright_red },
		-- GitSignsAddLn = { fg = colors.black, bg = colors.bright_green },
		-- GitSignsChangeLn = { fg = colors.black, bg = colors.cyan },
		-- GitSignsDeleteLn = { fg = colors.black, bg = colors.bright_red },
		-- GitSignsCurrentLineBlame = { fg = colors.white },
		--
		-- -- Telescope
		-- TelescopePromptBorder = { fg = colors.comment },
		-- TelescopeResultsBorder = { fg = colors.comment },
		-- TelescopePreviewBorder = { fg = colors.comment },
		-- TelescopeSelection = { fg = colors.white, bg = colors.selection },
		-- TelescopeMultiSelection = { fg = colors.purple, bg = colors.selection },
		-- TelescopeNormal = { fg = colors.fg, bg = colors.bg },
		-- TelescopeMatching = { fg = colors.green },
		-- TelescopePromptPrefix = { fg = colors.purple },
		-- TelescopeResultsDiffDelete = { fg = colors.red },
		-- TelescopeResultsDiffChange = { fg = colors.cyan },
		-- TelescopeResultsDiffAdd = { fg = colors.green },
		--
		-- -- NvimTree
		-- NvimTreeNormal = { fg = colors.fg, bg = colors.menu },
		-- NvimTreeVertSplit = { fg = colors.bg, bg = colors.bg },
		-- NvimTreeRootFolder = { fg = colors.fg, bold = true },
		-- NvimTreeGitDirty = { fg = colors.yellow },
		-- NvimTreeGitNew = { fg = colors.bright_green },
		-- NvimTreeImageFile = { fg = colors.pink },
		-- NvimTreeFolderIcon = { fg = colors.purple },
		-- NvimTreeIndentMarker = { fg = colors.nontext },
		-- NvimTreeEmptyFolderName = { fg = colors.comment },
		-- NvimTreeFolderName = { fg = colors.fg },
		-- NvimTreeSpecialFile = { fg = colors.pink, underline = true },
		-- NvimTreeOpenedFolderName = { fg = colors.fg },
		-- NvimTreeCursorLine = { bg = colors.selection },
		-- NvimTreeIn = { bg = colors.selection },
		--
		-- NvimTreeEndOfBuffer = endOfBuffer,
		--
		-- -- NeoTree
		-- NeoTreeNormal = { fg = colors.fg, bg = colors.menu },
		-- NeoTreeNormalNC = { fg = colors.fg, bg = colors.menu },
		-- NeoTreeDirectoryName = { fg = colors.fg },
		-- NeoTreeGitUnstaged = { fg = colors.bright_magenta },
		-- NeoTreeGitModified = { fg = colors.bright_magenta },
		-- NeoTreeGitUntracked = { fg = colors.bright_green },
		-- NeoTreeDirectoryIcon = { fg = colors.purple },
		-- NeoTreeIndentMarker = { fg = colors.nontext },
		-- NeoTreeDotfile = { fg = colors.comment },
		--
		-- -- Bufferline
		-- BufferLineIndicatorSelected = { fg = colors.purple },
		-- BufferLineFill = { bg = colors.black },
		-- BufferLineBufferSelected = { bg = colors.bg },
		-- BufferLineSeparator = { fg = colors.black },

return M
